language: python

matrix:
  fast_finish: true
  include:
    - language: python
      os: linux
      env:
        - PYTHON_VERSION="2.7"
        - JAVA_VERSION="8"
    - language: python
      os: linux
      env:
        - PYTHON_VERSION="3.6"
        - JAVA_VERSION="8"
    - language: python
      os: linux
      env:
        - PYTHON_VERSION="3.7"
        - JAVA_VERSION="8"
    - language: python
      os: linux
      env:
        - PYTHON_VERSION="3.7"
        - JAVA_VERSION="8"
        - RUN=sdist
    - language: python
      os: linux
      env:
        - PYTHON_VERSION="2.7"
        - JAVA_VERSION="9"
    - language: python
      os: linux
      env:
        - PYTHON_VERSION="3.6"
        - JAVA_VERSION="9"
    - language: python
      os: linux
      env:
        - PYTHON_VERSION="3.7"
        - JAVA_VERSION="9"


install:
  - sudo apt-get update
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - echo ". $HOME/miniconda/etc/profile.d/conda.sh" >> $HOME/.bashrc
  - source $HOME/.bashrc
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda config --add channels conda-forge
  - conda update -q conda
  - conda info -a
  - conda create -n jnius_env python=$PYTHON_VERSION
  - conda activate jnius_env
  - conda install openjdk=$JAVA_VERSION cython nose ant pip setuptools six

script:
  - conda activate jnius_env
  - if [ "$RUN" == "sdist" ]; then
      if [ "$PYJNIUS_DEPLOY" == "1" ]; then
        conda install twine;
        python setup_sdist.py sdist;
        python -m twine upload dist/*;
      fi;
    else
      make && make tests;
    fi;
